const SETTINGS = {
    guiaAnalise: 'dados',
    preparo2aPegadaDP: false,
    aplicarFormatacaoNoCsv: true,
    geraEntradaIntervalos: true,
    geraEntradaRecolhidas: true,
    atividades: { produtiva: "01", troca_turno: "10", recolhe: "11" },
    tipoProdutivo: "P",
    tipoOcioso: "O",
    sequenciaNormal: ["A", "B", "D", "E", "F"],
    sequenciaPosIntervalo: ["C", "G", "H", "I"],
    cells: {
        codProg: "C2",
        codLinha: "C3",
        codIda: "C4",
        codVolta: "C5",
        tempoPreparo: "C6",
        tempoAcesso: "C7",
        tempoRecolhe: "C8",
        horaCorteTurno: "C9",
        primeiroCodViagem: "C10",
        codLocalPegada: "C11",
    },
    viagensConf: {
        intervaloGeral: "I4:AV28",
        intervaloDuplaPegada: "G2:G28",
        intervaloExcecoes: "A35:J55",
        linhaCarroID: 1,
        linhaSentido: 2,
        linhaLocalidade: 3,
        linhasTrocaTurno: [29, 30, 31],
    },
    layout: [
        { field: "COD_PROG", size: 7, pad: " ", align: "L", resolve: (ctx) => ctx.prog },
        { field: "TAB",     size: 3, pad: " ", align: "L", resolve: (ctx) => ctx.tab },
        { field: "TURN",       size: 1, pad: " ", align: "L", resolve: (ctx) => ctx.turn },
        { field: "INICIO",     size: 5, pad: " ", align: "L", type: "hour", resolve: (ctx) => ctx.tabStart },
        { field: "TERM",       size: 5, pad: " ", align: "L", type: "hour", resolve: (ctx) => ctx.tabEnd },
        { field: "COD_PEGADA", size: 5, pad: "0", align: "R", resolve: (ctx) => ctx.pegada },
        { field: "PREPARO",    size: 2, pad: "0", align: "R", resolve: (ctx) => ctx.preparo },
        { field: "INIC_GAR",   size: 5, pad: " ", align: "L", type: "hour", resolve: (ctx) => ctx.garageStart },
        { field: "SENTIDO",        size: 1, pad: " ", align: "L", resolve: (ctx) => ctx.direction },
        { field: "COD",        size: 2, pad: "0", align: "R", resolve: (ctx) => ctx.seq },
        { field: "SAIDA",          size: 5, pad: " ", align: "L", resolve: (ctx) => ctx.start },
        { field: "CHEGADA",        size: 5, pad: " ", align: "L", resolve: (ctx) => ctx.end },
        { field: "ATIV",  size: 2, pad: "0", align: "R", resolve: (ctx) => ctx.activity },
        { field: "COD_LOCAL",  size: 5, pad: "0", align: "R", resolve: (ctx) => ctx.localCode },
        { 
            field: "COD_LINHA",      
            size: 3, 
            pad: " ", 
            align: "R", 
            resolve: (ctx) => ctx.isExcecaoLinha ? ctx.lin : "" 
        },
    ]
};